service: templateservice

package:
  individually: true

provider:
  name: aws
  runtime: provided
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  httpApi:
    payload: "2.0"
  logs:
    httpApi: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
  lambdaHashingVersion: 20201221

functions:
  myFirstLambdaFunction:
    handler: myFirstLambdaFunction
    package:
      individually: true
      artifact: .build/lambda/myFirstLambdaFunction/myFirstLambdaFunction.zip
    memorySize: 128
    events:
      - httpApi:
          method: GET
          path: /first
  mySecondLambdaFunction:
    handler: mySecondLambdaFunction
    package:
      individually: true
      artifact: .build/lambda/mySecondLambdaFunction/mySecondLambdaFunction.zip
    memorySize: 128
    events:
      - httpApi:
          method: GET
          path: /second
